/* AUTO-GENERATED BY Z-SCANNER - DO NOT EDIT */
#ifndef Z_REGISTRY_H
#define Z_REGISTRY_H

/* Vectors */
#define Z_AUTOGEN_VECS(X) \
    X(int, Int) \
    X(Point, Point) \

/* Lists */
#define Z_AUTOGEN_LISTS(X) \
    /* No lists found */

/* Maps */
#define Z_AUTOGEN_MAPS(X) \
    /* No maps found */

#endif // Z_REGISTRY_H
