/* AUTO-GENERATED BY Z-SCANNER - DO NOT EDIT */
#ifndef Z_REGISTRY_H
#define Z_REGISTRY_H

/* Vectors */
#define Z_AUTOGEN_VECS(X) \
    X(SensorData, Data) \
    X(int, Int) \
    X(Point, Point) \

/* Lists */
#define Z_AUTOGEN_LISTS(X) \

/* Maps */
#define Z_AUTOGEN_MAPS(X) \

/* Stable Maps */
#define Z_AUTOGEN_STABLE_MAPS(X) \

#endif // Z_REGISTRY_H
